---
title: "Homework 5- Due 11/30/2022"
author: "Lexi Keene"
date: '2022-11-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(tigris)
library(sf)
library(forcats)
library(ggthemes)
```

```{r, load data}
list.files("../data/")
homicide_data <- read_csv("../data/homicide-data.csv")
head(homicide_data)
```

```{r, clean data}
baltimore_data <- homicide_data %>% 
  filter(city == "Baltimore") %>% 
  mutate(reported_date = ymd(reported_date),
         year = year(reported_date),
         month = month(reported_date),
         day = day(reported_date)) %>% 
  mutate(solved = disposition == "Closed by arrest",
         solved = as.factor(solved),
         solved = recode(solved, "FALSE" = "Unsolved", "TRUE" = "Solved"),
         victim_race = as.factor(victim_race),
         victim_race = fct_lump(victim_race, n = 3))

```

```{r, make sf objects}
baltimore_tracts <- tracts("MD", "Baltimore city")

baltimore_sf  <- st_as_sf(baltimore_data, coords = c("lon", "lat")) %>% 
  st_set_crs(4269)
  
```


```{r, choice 1 figure}
ggplot() +
  geom_sf(data = baltimore_tracts) +
  geom_sf(data = baltimore_sf, aes(color = victim_race), alpha = 0.6) +
  facet_grid(. ~ solved) +
  theme_tufte() +
  labs(color = "Victim Race")
```
